version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
  api:
    build: ./api
    ports:
      - "5001:5001"
  db:
    image: firestore
    build:
        context: api
        dockerfile: Dockerfile.firestore
    volumes: