services:
  fastapi:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: /bin/sh -c "npm install -g npm@latest && npm install && npm run dev"